name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  rust:
    runs-on: codeberg-small
    container:
      image: rust:1.90
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check formatting
        run: cargo fmt --check

      - name: Test
        run: cargo test

      - name: Build release
        run: cargo build --release
