prompt = "bold #8abeb7"
hr = "#666666"
assistant = "#d4d4d4"
thinking = "#808080"
tool = "bold #d4d4d4"
tool_output = "#808080"
status = "#666666"
highlight = "#f0c674"
success = "#b5bd68"
warning = "#ffff00"
error = "#cc6666"

diff_added = "#b5bd68"
diff_removed = "#cc6666"
diff_hunk = "#81a2be"
diff_meta = "#808080"
